### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
This PR fixes the following issues:
 - Update Janino
 - Update DarkLaf to stable 2.7.1 release
 - Force Antialiasing at the manually rendered `class/jar/...` text
 - Fix the file drop that I accidentally broke at some point (oops)

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
Updated DarkLaf to stable 2.7.1. Every known issue is fixed now and this PR is ready to get merged.

**Comment by ThexXTURBOXx** [comment]
Addendum: CI/CD keeps failing because of https://github.com/weisJ/darklaf/issues/257. We will need to wait a little bit more until DarkLaf doesn't depend on a snapshot anymore.

**Comment by ThexXTURBOXx** [comment]
Forgot to comment about the new commit:
`DarkLaf 2.7.2` fixed the last issue as well. Now, everything seems to be stable and working correctly.
Finally really ready to get merged!

**Comment by Konloch** [comment]
Thank you!

**Pull request merged**
