### PR TITLE
Fix compiling and running with Java 9

### PR DESCRIPTION
**Pull request by games647**
Although this project might not be ready to decompile Java 9 jar files, it should be able to run and compile with Java 9 JVM. This fixes a few issues I encountered like the following:

1. The xml.Base64 class was replaced with java.util.Base64 (only available from java 8+ -> use apache codecs implementation)
2. Resources.class.getClass() is redundant and even returned a NPE everytime
3. Basic generics for TreeNode were added and therefore cannot make an unchecked cast

### CODE REVIEW

**Comment by Konloch** [comment]
Cheers, I've started implementing the changes. I'll try to get Java 9.x support working by this weekend.

**Comment by sh1ftchg** [comment]
Should we bother with java 9? Java 10 is out! Plus there's not really any changes needed, everything can still be compiled for Java 8; really just need to add "module-info.java" into packages and the appropriate "exports/requires". Beyond that, not much to change to run on java 9/10.

**Comment by games647** [comment]
>Should we bother with java 9? Java 10 is out! 

It's about Java 9+ not Java 9 alone. There were some breaking changes in Java 9.

>everything can still be compiled for Java 8

Not with JDK9+ (installed) and you cannot run it with Java 9+ runtime, because of missing classes. 

>really just need to add "module-info.java" into packages and the appropriate "exports/requires"

This PR still compiles against Java 8.

**Comment by sh1ftchg** [comment]
Not sure what classes are missing, the sun package was refactored into java/jdk packages... Nothing I can find is actually missing?

AFAIK the things that moved *shouldn't have been used in the first place*, internal java/jdk classes *can* be used but it's not standard. Correct me if I'm won't but you're supposed to reference them through their service provider interfaces (SPI's), not by the classes themselves. If you do that the code should work fine on java 8+.

**Comment by games647** [comment]
>Not sure what classes are missing, the sun package was refactored into java/jdk packages... Nothing I can find is actually missing? 

>If you do that the code should work fine on java 8 or newer.

Sadly, not only `**sun.*` packages were removed. 

[`javax.xml.bind.DatatypeConverter#parseBase64Binary(String)`](https://docs.oracle.com/javase/7/docs/api/javax/xml/bind/DatatypeConverter.html#parseBase64Binary(java.lang.String))

This class is now only available using an additional startup parameter:
`--add-modules java.xml.bind` or something similar.

Try to run the project with a Java 9 runtime and you'll get NoClassDefError. See [this](https://github.com/checkstyle/checkstyle/issues/5027) for example. We can now use the Base64 class in Java 8 or the class in commons-codec like mentioned in the first post. 

AFAIK this class or package **wasn't deprecated**, but it was still removed from the standard accessible library.

**Comment by Konloch** [comment]
Thanks for the suggestions guys but we need to explicitly support JDK 9 as games647 pointed out

**Pull request closed without merging**
