### PR TITLE
[Draft] Migrate to Maven and fix Code Style

### LINKED ISSUE #268: Support new java
Hello.  Will there be support for new versions of Java?

### LINKED ISSUE #269: java 14
Bytecode Viewer Version: 2.9.22, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 14

java.lang.IllegalArgumentException: Unsupported class file major version 58
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at the.bytecode.club.bytecodeviewer.util.JarUtils.getNode(JarUtils.java:260)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$8.run(BytecodeViewer.java:922)

### LINKED ISSUE #282: Update to cfr 0.150
Please update cfr to version 0.150 (https://www.benf.org/other/cfr/).

### LINKED ISSUE #289: Instructions to compile
As the gradle build PR is apparantly abandoned, here is a linux bash script to create a fat jar.

7z is used as backup because zip complains about jd-gui having multiple identical entries and aborting.
Requires linux packages `p7zip-full` and `zip` additionally to jdk.

Script for automatic building:
```
mkdir out || true
cd out
mkdir classes || true
cd ..

find src -name '*.java' -print > out/source.list

javac -cp "libs/*" -d out -encoding UTF-8 -g -sourcepath src -verbose @out/source.list

cd libs
for file in *.jar
do
	unzip -qo "$file" -x META-INF/* module-info.class -d ../out || 7z x -y -o../out -bd "$file"
done
cd ..

cd out
find . -type f -not -name '*.list' -print > classes.list
cd ..

cd out
jar cfe BytecodeViewer.jar the.bytecode.club.bytecodeviewer.BytecodeViewer @classes.list

zip -j9 BytecodeViewer.jar ../libs/*.txt ../libs/*.zip
cd ..

cd src
find . -type f -not -name "*.java" -exec zip -9 ../out/BytecodeViewer.jar {} +
cd ..
```

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
This PR also contains #288 and #266

The project has mostly been migrated to Maven (it is able to compile on my machine at least. It reports a build failure, but it built successfully anyways).

This way, updating most libraries was pretty easy and, thus, some decompilers even support newer Java versions (e.g. Java 14 records can be decompiled with CFR now)

Also, this PR fixes the Code Style everywhere as far as humanly possible (for me at least, I spent 10 hours working on this project at the time of writing this lol).

Please test and review, thank you :) This PR will help the community to develop this application easier and further.

Fixes #289 
Fixes #282
Fixes #269 
Fixes #268

### CODE REVIEW

**Comment by Janmm14** [comment]
So why is Krakatau a jar file now?

**Comment by ThexXTURBOXx** [comment]
Because the addjar plugin only wants to shade jar files into the executable. It's just a stupid workaround to get it to work...
But that doesn't matter as many things are technically very flawed with this project's setup (using system scope libraries, using modified libraries and so on)
If you have any better idea on how to do achieve this, I am very open for any suggestions

**Comment by Janmm14** [comment]
> Because the addjar plugin only wants to shade jar files into the executable. It's just a stupid workaround to get it to work...
> But that doesn't matter as many things are technically very flawed with this project's setup (using system scope libraries, using modified libraries and so on)
> If you have any better idea on how to do achieve this, I am very open for any suggestions

Just put it in src/main/resources

**Comment by ThexXTURBOXx** [comment]
Done. But I have to say that I definetly prefer the old way :P

**Comment by heisluft** [comment]
I think the pr should be based of the current master instead of other PRs if those are not mandatory to this specific pr as it obscures the patch. Furthermore the other PRs should be decided upon and merged seperatly, although this may be just my understanding of PRs .

On a side note:
I think it should be noted that a pr for migrating to gradle already exists hence we should open a RFC of some kind to decide between the two or just let @Konloch decide. Personally I prefer gradle because of its conciseness, build speed and its wrapper system which automatically sets up a local distro of gradle instead of requiring you to have it pre-installed (like maven does).

**Comment by ThexXTURBOXx** [comment]
I included #288 as I wanted to update ASM anyway, but didn't want to change the constants and variables needed for this myself :P
That's why I also included the other PR (it just didn't matter anymore).

The reason why I made this PR in the first place: I wanted people to be able to create patches of this project themselves as it hadn't been updated in quite a while. Also, the other PR you are talking about is pretty outdated and has many merge conflicts.
So, this PR is just a modernization of the other one, this time using Maven on the other hand.
I prefer Maven as it is the system I learned first and am much more confident fiddling around with. Gradle is untransparent in many cases - at least in my opinion (don't want to start a fight about which one might be superior, though).

That's also the reason, why I marked this PR as a draft -> To let people know, this something that might not get merged very soon until the author replied to either one of the two PRs

**Comment by heisluft** [comment]
That sounds sensible. Is your fork open to further prs?

**Comment by ThexXTURBOXx** [comment]
Of course, every PR is welcome :)

**Comment by ThexXTURBOXx** [comment]
This PR also now cleans up the entire codebase :)

**Comment by Konloch** [comment]
I still have to fully test everything but from what I've been able to test it looks like everythings working as intended, thank you and great work!

**Pull request merged**
