### PR TITLE
Added Allatori string deofuscator

### PR DESCRIPTION
**Pull request by Szperak**
BytecodeViewer is the best tool for working with bytecode I've found, but there was some bugs (probably fixed).
TODO: Add safe-reflection deobfuscation.

### CODE REVIEW

**Comment by Konloch** [comment]
<3

**Comment by Szperak** [comment]
<3

**Comment by Szperak** [comment]
In comments for AllatoriDecrypter class, there is still
* Coming soon.

and

* The UI for replace strings plugin.
in AllatoriStringDecrypterOptions

**Comment by Konloch** [comment]
Yeah if you could pass me one that would be great, I've been swamped with work lately but when I'm free I'll do some fixing and push 2.9.9-preview3.

Cheers!

**Comment by Szperak** [comment]
http://mchc.pl/mchc/1.7.10.mchc.jar

The most fancy class is RJ
(Run decrypter for class RJ instead of * )

And yes, It's a minecraft mod.

**Pull request merged**
