### PR TITLE
Fix I/O errors if working directory and settings file doesn't exist. Add saving and loading general settings, GUI size, panes and etc. Add methods list. Add synchronize viewing.

### PR DESCRIPTION
**Pull request by DreamSworK**
+ Fix I/O errors if working directory and settings file doesn't exist.
+ Update decompilers.
+ Add saving and loading general settings, GUI size, panes and etc.

### CODE REVIEW

**Comment by DreamSworK** [comment]
Add saving and loading general settings, GUI size, panes and etc.

**Comment by DreamSworK** [comment]
Add methods list, Add synchronize viewing (Panes), Add other improvements

**Comment by DreamSworK** [comment]
Add latest release 3.0.0
https://github.com/DreamSworK/bytecode-viewer

**Comment by DreamSworK** [comment]
[BytecodeViewer-3.0.0.zip](https://github.com/Konloch/bytecode-viewer/files/999216/BytecodeViewer-3.0.0.zip)

**Comment by federicodotta** [comment]
Hi DreamSwork! Thank you for having updated this great tool! 
I tried your release but I have an issue: the tool does not put the classes contained in the dex in the folder tree in the "Files" tab in the top-left part of the GUI (I have only resources, manifest, etc.) . I tried also to update dex2jar but with the same issue. I'm using the tool on Windows 10 64bit. I tried with more than one apk with the same result.

Thank you a lot for your help!

**Comment by Konloch** [comment]
Great work on the method list and the synchronized viewers (this is awesome!), I've been able to port these changes over to v2.9.16, I will push that update very soon, thank you for your contributions.

**Pull request closed without merging**
