### PR TITLE
Provide more modern icons

### PR DESCRIPTION
**Pull request by weisJ**
Replace the old icons with more modern looking ones, which also integrate a lot better with the theming system.
Relates to #413 

**Note**: This PR currently uses some minor fixes from darklaf version `3.0.1-SNAPSHOT`. This version will be released shortly.

How the new icons look (In order: Light, Dark, One Dark, Solarized Light, Solarized Dark, High Contrast Light, High Contrast Dark):

For some icons I wasn’t quite sure what to choose. Feedback welcome :)!

### CODE REVIEW

**Comment by weisJ** [comment]
The icon for `.sh` should actually be the same as the one for `.bat`. I slipped up while creating the preview images and left some test icon in there accidentally.

**Comment by GraxCode** [comment]
Maybe implement some icons for the tree expand all / close all buttons too (and make them borderless?).

**Comment by weisJ** [comment]
If you can point me to where I can find those icons in the ui of course :D

**Comment by ThexXTURBOXx** [comment]
That looks very nice, thanks! :)
However, if I may ask, why was `darklaf-extensions-rsta` downgraded again?

**Comment by weisJ** [comment]
Looks like a rebase-mistake. I’ll fix when I get home.

**Comment by Konloch** [comment]
Amazing work on this!

**Pull request merged**
